jobapp/urls.py
from django.urls import path
from .views import *

app_name = "jobapp"

urlpatterns = [

    path('', JobSeekerHomeView.as_view(), name='jobseekerhome'),
    path('jobseeker/registration/', JobSeekerRegistrationView.as_view(),
         name='jobseekerregistration'),
    path('job/list/', JobListView.as_view(), name='joblist'),
    path('job/<int:pk>/detail/', JobDetailView.as_view(),
         name='jobdetail'),  # primary key is mandatory for detail
    path('job/<int:pk>/apply/', JobSeekerJobApplyView.as_view(),
         name='jobseekerjobapply'),  # primary key to take job

    path('login/', LoginView.as_view(), name='login'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),




    # for employer section

    path('employer/registration/', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('employer/home/', EmployerHomeView.as_view(), name='employerhome'),
    path('employer/profile/',
         EmployerProfileView.as_view(), name='employerprofile'),

    path('employer/job/<int:pk>/detail/',
         EmployerJobDetailView.as_view(), name='employerjobdetail'),\

    path('employer/job/post/', EmployerJobCreateView.as_view(),
         name='employerjobcreate'),


]

jobproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/employertemplates/employerbase.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title></title>
</head>
<body>

	{% block content %}


	{% endblock %}

</body>
</html>

templates/employertemplates/employerhome.html
{% extends 'employertemplates/employerbase.html' %}
{% load static %}


{% block content %}
<h1>This is employer home page......</h1>
<a href="{% url 'jobapp:employerprofile' %}">My Profile</a>
<a href="{% url 'jobapp:employerjobcreate' %}">Post A New Job</a>











{% endblock %}

templates/employertemplates/employerjobcreate.html
{% extends 'employertemplates/employerbase.html' %}
{% load static %}

{% block content %}

<form method="POST" enctype="multipart/form-data">

	{% csrf_token %}
	{{form.as_p}}
	<button>Submit Job</button>

</form>









{% endblock %}

templates/employertemplates/employerjobdetail.html
{% extends 'employertemplates/employerbase.html' %}
{% load static %}

{% block content %}

<h3>Job Title:{{jobobject.title}}</h3><br>
<h3>Job Catagory:{{jobobject.catagory.title}}</h3><br>
<h3>Job Deadline:{{jobobject.deadline}}</h3><br>

<h2>Job Applicants for this Job</h2><hr>
<table class="table">

	<thead>
		<tr>
			<th>S.N</th>
			<th>Applicants</th>
			<th>Applied_On</th>
			<th>Download CV</th>
		</tr>
	</thead>
	<body>
		{% for application in jobobject.jobapplication_set.all %}  <!-- reverse relation between Job and Job application -->
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{application.jobseeker}}</td>
				<td>{{application.created_at}}</td>
				<td><a href="{{application.jobseeker.cv.url}}" download>Download CV</a>
					<a href="{{application.cover_letter.url}}" dowanload> Download Cover Letter</a></td>
			</tr>

		{% endfor %}


	</body>
	




</table>












{% endblock %}

templates/employertemplates/employerprofile.html
{% extends 'employertemplates/employerbase.html' %}
{% load static %}

{% block content %}

	<h4>Name:{{employer.name}}</h4><br>
	<h4>Address:{{employer.address}}</h4><br>
	<h4>Mobile:{{employer.mobile}}</h4><br>
	<h4>Email:{{employer.email}}</h4><br>
	<h3>Job Posted by {{employer.company}} Company</h3>

	<table class="table">
		<thead>
			<tr>
				<th>S.N</th>			
				<th>Job Title</th>			
				<th>Deadline</th>			
				<th>Posted on</th>			
			</tr>
		</thead>
		<!-- reverse query relation employer ko object sanga dot .job(model name in small letter).all -->


		<tbody>
			{% for job in employer.job_set.all %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td><a href="{% url 'jobapp:employerjobdetail' job.pk %}">{{job.title}}({{job.jobapplication_set.count}} applications)</a></td> 
					<td>{{job.deadline}}</td>
					<td>{{job.created_at}}</td>

				</tr>
			{% endfor %}


			
		</tbody>
			
		
	</table>



{% endblock %}

templates/employertemplates/employerregistration.html
{% extends 'employertemplates/employerbase.html' %}
{% load static %}

{% block content %}

<h2>Do you want to register...??</h2>
<form method="POST" enctype='multipart/form-data'>

	{% csrf_token %}
	{{form.as_p}}
	<button>Register</button>
</form>








{% endblock%}