jobapp/urls.py
from django.urls import path
from .views import *

app_name = "jobapp"

urlpatterns = [

    path('', JobSeekerHomeView.as_view(), name='jobseekerhome'),
    path('jobseeker/registration/', JobSeekerRegistrationView.as_view(),
         name='jobseekerregistration'),
    path('job/list/', JobListView.as_view(), name='joblist'),
    path('job/<int:pk>/detail/', JobDetailView.as_view(),
         name='jobdetail'),  # primary key is mandatory for detail
    path('job/<int:pk>/apply/', JobSeekerJobApplyView.as_view(),
         name='jobseekerjobapply'),  # primary key to take job

    path('login/', LoginView.as_view(), name='login'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),




    # for employer section

    path('employer/registration/', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('employer/home/', EmployerHomeView.as_view(), name='employerhome'),
    path('employer/profile/',
         EmployerProfileView.as_view(), name='employerprofile'),

    path('employer/job/<int:pk>/detail/',
         EmployerJobDetailView.as_view(), name='employerjobdetail'),\

    path('employer/job/post/', EmployerJobCreateView.as_view(),
         name='employerjobcreate'),


]

jobproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/jobseekertemplates/jobdetail.html
	{% extends 'jobseekertemplates/jobseekerbase.html' %}
	

	{% block content %}

		<div class="row">


					<div class="col-md-4">

							<p><h2><b>Job Title:-{{jobdetail.title}}</b></h2></p>
							<img src="{{jobdetail.image.url}}"   height='300' width="300">
							<h5>Location:{{jobdetail.job_location}}</h5>
							<p class="font-italic"><h5>Salary:Rs-</h5> <b>{{jobdetail.salary}}</b></p>


					</div>


		</div>

		<a href="{% url 'jobapp:jobseekerjobapply' jobdetail.id %}"><button>Apply</button></a>  <!-- #id is used for the specific job passed with contextobj name  -->

		
	{% endblock %}

templates/jobseekertemplates/joblist.html
	{% extends 'jobseekertemplates/jobseekerbase.html' %}

	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">


	{% block content %}

	<h1>Here are the list of jobs...</h1>

		<div class="row">

					{% for job in joblist %}

					<div class="col-md-4">

							<p> <h4><b>Job Title-<a href="{% url 'jobapp:jobdetail' job.id %}">{{job.title}}</b></h4></a></p>
							<img src="{{job.image.url}}"   height='300' width="300">


					</div>

					{% endfor %}

		</div>

		
			


 





	{% endblock %}

templates/jobseekertemplates/jobseekerbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>	
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<title></title>
</head>
<body>



  <!-- #to show the logged in user -->  <!-- and  -->  <!-- logged in user ko name chai jobseeker hunuparyo  means loggedin ko group check gareko-->



  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">JobApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'jobapp:jobseekerhome' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'jobapp:joblist' %}">JobList</a>
      </li>
        {% if request.user.is_authenticated  and request.user.groups.first.name == 'jobseeker' %}

          <h3>Logged in as:{{request.user}}</h3>
          <li  class="nav-item">
            
            <a  class="nav-link" href="{% url 'jobapp:jobseekerprofile' %}">My profile</a>
          </li>

        {% else %}
        <li class="nav-item active">
              <a class="nav-link" href="{% url 'jobapp:login' %}">Login<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'jobapp:jobseekerregistration' %}">Register</a>
            </li>

        {% endif %}
    </ul>
  </div>
</nav>

  	 <!-- <a href="{% url 'jobapp:jobseekerregistration' %}">Register</a> -->
  	<!-- <a href="{% url 'jobapp:joblist' %}">JobList</a> -->




  
{% block content %}


{% endblock %}



</body>
</html>

templates/jobseekertemplates/jobseekerhome.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}

{% load static %}



{% block content %}

<div class="row">
	{% for jobitem in joblist %}

	<div class="col-md-3">
		
	
		<h3>{{jobitem.employer}}</h3>
		<div class="card" style="width: 18rem;">
		  <img class="card-img-top" src="..." alt="Card image cap">
		  <div class="card-body">
		    <h5 class="card-title"><h3>{{jobitem.title}}</h3></h5>
		    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
		    <a href="{% url 'jobapp:jobdetail' jobitem.id%}" class="btn btn-primary">Job Description</a>
		  </div>
		</div>	
	</div>
	{% endfor %}
	
</div>







{% endblock %}

templates/jobseekertemplates/jobseekerjobapply.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}

{% load static %}


{% block content %}



<h1>Job Application Form</h1>

<form method="POST" enctype="multipart/form-data" >   <!-- #enctype for upload the file and accepted the file by this form --><!--  post method needs csrf token -->
	{% csrf_token %}
	{{ form.as_p}}
	<button>Apply</button>
</form>


{% endblock %}

templates/jobseekertemplates/jobseekerlogin.html
{% extends "jobseekertemplates/jobseekerbase.html" %}
{% load static %}
{% block content %}
<br>
<style type="text/css">
	.login{
			text-align: center;

	}
	

</style>

{% if error %}
	<li class="text-danger">{{error}}</li>
{% endif %}	
 <form method = "POST">
 	{% csrf_token %}
	 <div class="login">
	    <h1>Login</h1>	
	 	{{ form.as_p }}
	 	<button>Login</button>
	 </div>	

 </form>

<h4>Sign Up Here As:</h4>
<a href="{% url 'jobapp:jobseekerregistration' %}">JobSeeker</a><hr>
<a href="{% url 'jobapp:employerregistration' %}">Employer</a>



{% endblock %}

templates/jobseekertemplates/jobseekerprofile.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% load static %}

{% block content %}
<h1>My profile</h1>
<h4>Name:{{jobseeker.name}}</h4><br>
<h4>Address:{{jobseeker.address}}</h4><br>
<h4>Mobile:{{jobseeker.mobile}}</h4><br>

<h2>Jobs I have Applied</h2>
<table class="table">
	<thead>
		<tr>
			<th>S.N</th>
			<th>Job Title</th>
			<th>Company</th>
			<th>Date</th>
		</tr>		
	</thead>





	<tbody>
		{% for jobappl in jobseeker.jobapplication_set.all %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{jobappl.job.title}}</td>
			<td>{{jobappl.job.employer.company}}</td>
			<td>{{jobappl.created_at}}</td>
		</tr>
		{% endfor %}

	</tbody>


</table>














{% endblock %}

templates/jobseekertemplates/jobseekerregistration.html
 {% extends 'jobseekertemplates/jobseekerbase.html' %}

{% load static %}

{% block content %}

<form method='POST' enctype='multipart/form-data'>

	{%  csrf_token %}
	{{form.as_p}}
	<button>Register</button>
	

</form>






{% endblock %}